#!/usr/bin/env python3

import argparse
import json
import shlex
import shutil
import sys
from pathlib import Path


VERSIONS = ("GC_1_2_5", "GC_1_2_5n")


def quote(value: object) -> str:
    return shlex.quote(str(value)).replace("$", "$$")


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)


def write_build_ninja(version: str, config_path: Path) -> None:
    python = quote(Path(sys.executable).resolve())
    config = quote(config_path)
    build_dir = Path("build") / version
    verified = build_dir / "verified.stamp"
    pe_info = build_dir / "pe-info.json"
    ghidra_stamp = build_dir / "ghidra.stamp"
    optimizer_analysis = build_dir / "optimizer-analysis.md"
    subsystem_inventory = build_dir / "subsystem-inventory.md"
    pcode_opcodes = build_dir / "pcode-opcodes.json"
    subsystem_manifest = Path("config") / version / "subsystems.json"
    subsystem_stamp = build_dir / "subsystems.stamp"
    source_stamp = build_dir / "sources.stamp"
    format_stamp = build_dir / "format.stamp"
    test_stamp = build_dir / "tests.stamp"
    source_files = sorted(Path("src").rglob("*.c"))
    source_dependencies = source_files + sorted(Path("include").rglob("*.h"))
    source_inputs = " ".join(quote(source) for source in source_dependencies)
    format_dependencies = source_dependencies + sorted(Path("tests").rglob("*.c"))
    format_inputs = " ".join(quote(source) for source in format_dependencies)
    subsystem_validation = ""
    subsystem_check = ""
    if subsystem_manifest.is_file():
        subsystem_validation = f"""
rule validate_subsystems
  command = $python tools/check_subsystems.py --config $config --manifest {quote(subsystem_manifest)} --stamp $out
  description = SUBSYSTEMS $in

build {subsystem_stamp}: validate_subsystems {subsystem_manifest} tools/check_subsystems.py tools/pe.py | {verified}
"""
        subsystem_check = quote(subsystem_stamp)

    text = f"""# Generated by configure.py. Do not edit.
ninja_required_version = 1.8
python = {python}
config = {config}

rule verify_original
  command = $python tools/verify_original.py --config $config --stamp $out
  description = VERIFY $in

rule pe_info
  command = $python tools/pe.py info --config $config --output $out
  description = PE-INFO $in

rule ghidra_import
  command = $python tools/ghidra_project.py import --config $config --stamp $out
  description = GHIDRA $in
  pool = console

rule ghidra_export_optimizer
  command = $python tools/ghidra_project.py export-optimizer --config $config --output $out
  description = GHIDRA-EXPORT $out
  pool = console

rule ghidra_export_subsystems
  command = $python tools/ghidra_project.py export-subsystems --config $config --output $out
  description = GHIDRA-EXPORT $out
  pool = console

rule export_pcode_opcodes
  command = $python tools/pcode_descriptors.py --config $config --output $out
  description = PCODE-OPCODES $out

rule check_sources
  command = $python tools/check_sources.py --stamp $out
  description = C-SYNTAX $in

rule check_format
  command = $python tools/check_format.py --stamp $out
  description = C-FORMAT $in

rule check_tests
  command = $python tools/check_tests.py --stamp $out
  description = MODEL-TEST $in

build {verified}: verify_original {config_path}
build {pe_info}: pe_info {config_path} | {verified}
build {ghidra_stamp}: ghidra_import {config_path} | {verified}
build {optimizer_analysis}: ghidra_export_optimizer tools/ghidra_scripts/ExportOptimizer.java | {ghidra_stamp}
build {subsystem_inventory}: ghidra_export_subsystems tools/ghidra_scripts/ExportSubsystems.java | {ghidra_stamp}
build {pcode_opcodes}: export_pcode_opcodes tools/pcode_descriptors.py tools/allocator_snapshot.py tools/pe.py tools/verify_original.py | {verified}
build {source_stamp}: check_sources tools/check_sources.py {source_inputs}
build {format_stamp}: check_format tools/check_format.py .clang-format {format_inputs}
build {test_stamp}: check_tests tools/check_tests.py tools/allocator_snapshot.py tools/allocator_provenance.py src/backend/Registers.c src/backend/Coloring.c src/backend/SpillCode.c tests/test_registers.c tests/test_coloring.c tests/test_spill_code.c tests/test_allocator_snapshot.py tests/test_allocator_provenance.py include/mwcc/Registers.h include/mwcc/Coloring.h include/mwcc/SpillCode.h include/mwcc/backend_types.h
{subsystem_validation}

build check: phony {verified} {pe_info} {pcode_opcodes} {source_stamp} {format_stamp} {test_stamp} {subsystem_check}
build ghidra: phony {ghidra_stamp}
build optimizer-analysis: phony {optimizer_analysis}
build subsystem-inventory: phony {subsystem_inventory}
build pcode-opcodes: phony {pcode_opcodes}

default check
"""
    Path("build.ninja").write_text(text, encoding="utf-8")


def write_objdiff(version: str) -> None:
    objects_path = Path("config") / version / "objects.json"
    objects = load_json(objects_path)
    units = []
    for unit in objects["units"]:
        units.append(
            {
                "name": unit["name"],
                "target_path": unit["target"],
                "base_path": unit.get("base"),
                "metadata": {
                    "complete": unit.get("complete", False),
                    "source_path": unit.get("source"),
                },
            }
        )

    objdiff = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "custom_make": "ninja",
        "custom_args": ["-d", "keeprsp"],
        "build_target": False,
        "build_base": True,
        "watch_patterns": ["*.c", "*.h", "*.py", "*.json", "*.csv"],
        "ignore_patterns": ["build/**/*", "orig/**/*"],
        "units": units,
    }
    Path("objdiff.json").write_text(
        json.dumps(objdiff, indent=2) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate MWCC decomp build files")
    parser.add_argument("--version", choices=VERSIONS, default=VERSIONS[0])
    args = parser.parse_args()

    config_path = Path("config") / args.version / "config.json"
    if not config_path.is_file():
        parser.error(f"missing {config_path}")
    if shutil.which("ninja") is None:
        parser.error("ninja is required")

    write_build_ninja(args.version, config_path)
    write_objdiff(args.version)
    print(f"Configured {args.version}")


if __name__ == "__main__":
    main()
